let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Shoe 1",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Shoe 2",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Shoe 3",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Shoe 4",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-4.jpg",
  },

  {
    id: "thyfapbcv",
    name: "Shoe 5",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-5.jpg",
  },
  {
    id: "ghfjdcbcv",
    name: "Shoe 6",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-6.jpg",
  },
  {
    id: "thyfhcbfv",
    name: "Shoe 7",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-7.jpg",
  },
  {
    id: "thyffhjdv",
    name: "Shoe 8",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-8.jpg",
  },
  {
    id: "tjffhcbcv",
    name: "Shoe 9",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-9.jpg",
  },
  {
    id: "thyfjcbcv",
    name: "Shoe 10",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-10.jpg",
  },
  {
    id: "fhjskdlsj",
    name: "Shoe 11",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-11.jpg",
  },
  {
    id: "fhgjdkays",
    name: "Shoe 12",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-12.jpg",
  },
];
